<template>
  <q-page class="q-pa-md page-shell">
    <div class="row items-center justify-between q-mb-md q-col-gutter-md"><div><div class="text-h4 text-weight-bold text-primary">Citas</div><div class="text-subtitle2 text-grey-7">Agenda de servicios técnicos</div></div><div class="q-gutter-sm"><q-btn color="primary" icon="add" label="Nueva Cita" @click="abrirCrear" /><q-btn color="primary" outline icon="refresh" label="Actualizar" @click="cargarCitas" /></div></div>
    <q-card class="content-card q-mb-md"><q-card-section class="row q-col-gutter-md"><div class="col-12 col-md-8"><q-input v-model="buscar" outlined dense clearable debounce="400" label="Buscar cita" @update:model-value="cargarCitas"><template #prepend><q-icon name="search" /></template></q-input></div><div class="col-12 col-md-4"><q-select v-model="estadoFiltro" outlined dense clearable label="Filtrar estado" :options="estadoOptions" emit-value map-options @update:model-value="cargarCitas" /></div></q-card-section></q-card>
    <q-banner v-if="error" class="bg-red-1 text-red q-mb-md rounded-borders">{{ error }}</q-banner>
    <q-card class="content-card"><q-table title="Listado de citas" :rows="citas" :columns="columns" row-key="id" :loading="loading" no-data-label="No hay citas registradas"><template #body-cell-total="props"><q-td :props="props">Bs {{ Number(props.row.total || 0).toFixed(2) }}</q-td></template><template #body-cell-estado="props"><q-td :props="props"><q-chip dense :color="colorEstado(props.row.estado)" text-color="white">{{ textoEstado(props.row.estado) }}</q-chip></q-td></template><template #body-cell-acciones="props"><q-td :props="props" class="table-actions"><q-btn dense flat round color="primary" icon="visibility" @click="abrirVer(props.row)" /><q-btn dense flat round color="warning" icon="edit" @click="abrirEditar(props.row)" /><q-btn dense flat round color="positive" icon="check_circle" @click="finalizarCita(props.row)" /><q-btn dense flat round color="negative" icon="delete" @click="eliminarCita(props.row)" /></q-td></template></q-table></q-card>
    <q-dialog v-model="dialogo"><q-card class="rounded-dialog" style="width: 850px; max-width: 95vw"><q-card-section class="bg-primary text-white"><div class="text-h6">{{ tituloDialogo }}</div></q-card-section><q-card-section class="row q-col-gutter-md"><div class="col-12 col-md-4"><q-select v-model="form.cliente_id" :options="clientesOptions" emit-value map-options label="Cliente" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-4"><q-select v-model="form.tecnico_id" :options="tecnicosOptions" emit-value map-options label="Técnico" outlined clearable :readonly="modo === 'ver'" /></div><div class="col-12 col-md-4"><q-select v-model="form.servicio_id" :options="serviciosOptions" emit-value map-options label="Servicio" outlined clearable :readonly="modo === 'ver'" @update:model-value="seleccionarServicio" /></div><div class="col-12 col-md-3"><q-input v-model="form.fecha" type="date" label="Fecha" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-3"><q-input v-model="form.hora" type="time" label="Hora" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-3"><q-select v-model="form.estado" :options="estadoOptions" emit-value map-options label="Estado" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-3"><q-input v-model.number="form.total" type="number" label="Total" prefix="Bs" outlined :readonly="modo === 'ver'" /></div><div class="col-12"><q-input v-model="form.descripcion" label="Descripción del trabajo" outlined type="textarea" :readonly="modo === 'ver'" /></div><div class="col-12"><q-input v-model="form.observacion" label="Observación" outlined type="textarea" :readonly="modo === 'ver'" /></div></q-card-section><q-card-actions align="right"><q-btn flat label="Cerrar" color="grey-8" v-close-popup /><q-btn v-if="modo !== 'ver'" color="primary" icon="save" :label="modo === 'crear' ? 'Guardar' : 'Actualizar'" @click="guardarCita" /></q-card-actions></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { date, useQuasar } from 'quasar'
import api, { extraerMensajeError } from '../services/api.js'
const $q = useQuasar()
const loading = ref(false), error = ref(''), buscar = ref(''), estadoFiltro = ref(null), citas = ref([]), clientes = ref([]), tecnicos = ref([]), servicios = ref([]), dialogo = ref(false), modo = ref('crear'), citaId = ref(null)
const estadoOptions = [{ label: 'Pendiente', value: 'pendiente' }, { label: 'En proceso', value: 'en_proceso' }, { label: 'Concluida', value: 'concluida' }, { label: 'Cancelada', value: 'cancelada' }]
const formInicial = { cliente_id: null, tecnico_id: null, servicio_id: null, fecha: date.formatDate(new Date(), 'YYYY-MM-DD'), hora: '08:00', estado: 'pendiente', descripcion: '', total: 0, observacion: '' }
const form = ref({ ...formInicial })
const clientesOptions = computed(() => clientes.value.map(c => ({ label: c.nombre, value: c.id })))
const tecnicosOptions = computed(() => tecnicos.value.map(t => ({ label: t.nombre, value: t.id })))
const serviciosOptions = computed(() => servicios.value.map(s => ({ label: `${s.nombre} - Bs ${Number(s.precio || 0).toFixed(2)}`, value: s.id, precio: Number(s.precio || 0) })))
const columns = [{ name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', sortable: true }, { name: 'hora', label: 'Hora', field: 'hora', align: 'left' }, { name: 'cliente', label: 'Cliente', field: row => row.cliente?.nombre || 'Sin cliente', align: 'left' }, { name: 'tecnico', label: 'Técnico', field: row => row.tecnico?.nombre || 'Sin técnico', align: 'left' }, { name: 'servicio', label: 'Servicio', field: row => row.servicio?.nombre || 'Sin servicio', align: 'left' }, { name: 'total', label: 'Total', field: 'total', align: 'right' }, { name: 'estado', label: 'Estado', field: 'estado', align: 'center' }, { name: 'acciones', label: 'Acciones', field: 'acciones', align: 'center' }]
const tituloDialogo = computed(() => modo.value === 'crear' ? 'Registrar cita' : modo.value === 'editar' ? 'Editar cita' : 'Ver cita')
const textoEstado = estado => estadoOptions.find(item => item.value === estado)?.label || estado
const colorEstado = estado => ({ pendiente: 'warning', en_proceso: 'info', concluida: 'positive', cancelada: 'negative' }[estado] || 'grey')
const limpiarFormulario = () => { form.value = { ...formInicial }; citaId.value = null }
const normalizarHora = hora => hora ? String(hora).slice(0, 5) : ''
const prepararFormulario = item => ({
  ...item,
  hora: normalizarHora(item.hora),
  cliente_id: item.cliente_id || item.cliente?.id || null,
  tecnico_id: item.tecnico_id || item.tecnico?.id || null,
  servicio_id: item.servicio_id || item.servicio?.id || null,
})
const cargarCombos = async () => { const [c, t, s] = await Promise.all([api.get('/clientes'), api.get('/tecnicos'), api.get('/servicios')]); clientes.value = c.data.data || []; tecnicos.value = t.data.data || []; servicios.value = s.data.data || [] }
const cargarCitas = async () => { loading.value = true; error.value = ''; try { const r = await api.get('/citas', { params: { buscar: buscar.value || undefined, estado: estadoFiltro.value || undefined } }); citas.value = r.data.data || [] } catch (err) { error.value = extraerMensajeError(err, 'No se pudo cargar la lista de citas.') } finally { loading.value = false } }
const seleccionarServicio = value => { const opt = serviciosOptions.value.find(s => s.value === value); if (opt && !form.value.total) form.value.total = opt.precio }
const abrirCrear = async () => { modo.value = 'crear'; limpiarFormulario(); await cargarCombos(); dialogo.value = true }
const abrirVer = async item => { modo.value = 'ver'; citaId.value = item.id; await cargarCombos(); form.value = prepararFormulario(item); dialogo.value = true }
const abrirEditar = async item => { modo.value = 'editar'; citaId.value = item.id; await cargarCombos(); form.value = prepararFormulario(item); dialogo.value = true }
const guardarCita = async () => { if (!form.value.cliente_id || !form.value.fecha) { $q.notify({ type: 'warning', message: 'Cliente y fecha son obligatorios' }); return } try { if (modo.value === 'crear') await api.post('/citas', form.value); else await api.put(`/citas/${citaId.value}`, form.value); $q.notify({ type: 'positive', message: 'Cita guardada correctamente' }); dialogo.value = false; limpiarFormulario(); cargarCitas() } catch (err) { $q.notify({ type: 'negative', message: extraerMensajeError(err, 'No se pudo guardar la cita') }) } }
const finalizarCita = item => { $q.dialog({ title: 'Finalizar cita', message: `¿Marcar como concluida la cita de ${item.cliente?.nombre || 'cliente'}?`, cancel: true, persistent: true }).onOk(async () => { try { await api.put(`/citas/${item.id}/finalizar`); $q.notify({ type: 'positive', message: 'Cita finalizada correctamente' }); cargarCitas() } catch (err) { $q.notify({ type: 'negative', message: extraerMensajeError(err, 'No se pudo finalizar la cita') }) } }) }
const eliminarCita = item => { $q.dialog({ title: 'Confirmar eliminación', message: `¿Eliminar esta cita?`, cancel: true, persistent: true }).onOk(async () => { try { await api.delete(`/citas/${item.id}`); $q.notify({ type: 'positive', message: 'Cita eliminada correctamente' }); cargarCitas() } catch (err) { $q.notify({ type: 'negative', message: extraerMensajeError(err, 'No se pudo eliminar la cita') }) } }) }
onMounted(() => { cargarCitas(); cargarCombos() })
</script>
