<template>
  <q-page class="q-pa-md page-shell">
    <div class="row items-center justify-between q-mb-md q-col-gutter-md"><div><div class="text-h4 text-weight-bold text-primary">Equipos</div><div class="text-subtitle2 text-grey-7">Equipos registrados por cliente</div></div><div class="q-gutter-sm"><q-btn color="primary" icon="add" label="Nuevo Equipo" @click="abrirCrear" /><q-btn color="primary" outline icon="refresh" label="Actualizar" @click="cargarEquipos" /></div></div>
    <q-card class="content-card q-mb-md"><q-card-section><q-input v-model="buscar" outlined dense clearable debounce="400" label="Buscar por tipo, marca, modelo, serie o cliente" @update:model-value="cargarEquipos"><template #prepend><q-icon name="search" /></template></q-input></q-card-section></q-card>
    <q-banner v-if="error" class="bg-red-1 text-red q-mb-md rounded-borders">{{ error }}</q-banner>
    <q-card class="content-card"><q-table title="Listado de equipos" :rows="equipos" :columns="columns" row-key="id" :loading="loading" no-data-label="No hay equipos registrados"><template #body-cell-activo="props"><q-td :props="props"><q-chip dense :color="props.row.activo ? 'positive' : 'grey'" text-color="white">{{ props.row.activo ? 'Activo' : 'Inactivo' }}</q-chip></q-td></template><template #body-cell-acciones="props"><q-td :props="props" class="table-actions"><q-btn dense flat round color="primary" icon="visibility" @click="abrirVer(props.row)" /><q-btn dense flat round color="warning" icon="edit" @click="abrirEditar(props.row)" /><q-btn dense flat round color="negative" icon="delete" @click="eliminarEquipo(props.row)" /></q-td></template></q-table></q-card>
    <q-dialog v-model="dialogo"><q-card class="rounded-dialog" style="width: 760px; max-width: 95vw"><q-card-section class="bg-primary text-white"><div class="text-h6">{{ tituloDialogo }}</div></q-card-section><q-card-section class="row q-col-gutter-md"><div class="col-12 col-md-6"><q-select v-model="form.cliente_id" :options="clientesOptions" emit-value map-options label="Cliente" outlined clearable :readonly="modo === 'ver'" /></div><div class="col-12 col-md-6"><q-input v-model="form.tipo" label="Tipo de equipo" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-4"><q-input v-model="form.marca" label="Marca" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-4"><q-input v-model="form.modelo" label="Modelo" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-4"><q-input v-model="form.serie" label="Serie" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-8"><q-input v-model="form.ubicacion" label="Ubicación" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-4"><q-toggle v-model="form.activo" label="Activo" :disable="modo === 'ver'" /></div><div class="col-12"><q-input v-model="form.observacion" label="Observación" outlined type="textarea" :readonly="modo === 'ver'" /></div></q-card-section><q-card-actions align="right"><q-btn flat label="Cerrar" color="grey-8" v-close-popup /><q-btn v-if="modo !== 'ver'" color="primary" icon="save" :label="modo === 'crear' ? 'Guardar' : 'Actualizar'" @click="guardarEquipo" /></q-card-actions></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { useQuasar } from 'quasar'
import api, { extraerMensajeError } from '../services/api.js'
const $q = useQuasar()
const loading = ref(false), error = ref(''), buscar = ref(''), equipos = ref([]), clientes = ref([]), dialogo = ref(false), modo = ref('crear'), equipoId = ref(null)
const formInicial = { cliente_id: null, tipo: '', marca: '', modelo: '', serie: '', ubicacion: '', observacion: '', activo: true }
const form = ref({ ...formInicial })
const clientesOptions = computed(() => clientes.value.map(c => ({ label: c.nombre, value: c.id })))
const columns = [{ name: 'cliente', label: 'Cliente', field: row => row.cliente?.nombre || 'Sin cliente', align: 'left' }, { name: 'tipo', label: 'Tipo', field: 'tipo', align: 'left', sortable: true }, { name: 'marca', label: 'Marca', field: 'marca', align: 'left' }, { name: 'modelo', label: 'Modelo', field: 'modelo', align: 'left' }, { name: 'ubicacion', label: 'Ubicación', field: 'ubicacion', align: 'left' }, { name: 'activo', label: 'Estado', field: 'activo', align: 'center' }, { name: 'acciones', label: 'Acciones', field: 'acciones', align: 'center' }]
const tituloDialogo = computed(() => modo.value === 'crear' ? 'Registrar equipo' : modo.value === 'editar' ? 'Editar equipo' : 'Ver equipo')
const limpiarFormulario = () => { form.value = { ...formInicial }; equipoId.value = null }
const cargarClientes = async () => { const r = await api.get('/clientes'); clientes.value = r.data.data || [] }
const cargarEquipos = async () => { loading.value = true; error.value = ''; try { const r = await api.get('/equipos', { params: { buscar: buscar.value || undefined } }); equipos.value = r.data.data || [] } catch (err) { error.value = extraerMensajeError(err, 'No se pudo cargar la lista de equipos.') } finally { loading.value = false } }
const abrirCrear = async () => { modo.value = 'crear'; limpiarFormulario(); await cargarClientes(); dialogo.value = true }
const abrirVer = async item => { modo.value = 'ver'; equipoId.value = item.id; await cargarClientes(); form.value = { ...item, cliente_id: item.cliente_id || item.cliente?.id || null }; dialogo.value = true }
const abrirEditar = async item => { modo.value = 'editar'; equipoId.value = item.id; await cargarClientes(); form.value = { ...item, cliente_id: item.cliente_id || item.cliente?.id || null }; dialogo.value = true }
const guardarEquipo = async () => { if (!form.value.tipo) { $q.notify({ type: 'warning', message: 'El tipo de equipo es obligatorio' }); return } try { if (modo.value === 'crear') await api.post('/equipos', form.value); else await api.put(`/equipos/${equipoId.value}`, form.value); $q.notify({ type: 'positive', message: 'Equipo guardado correctamente' }); dialogo.value = false; limpiarFormulario(); cargarEquipos() } catch (err) { $q.notify({ type: 'negative', message: extraerMensajeError(err, 'No se pudo guardar el equipo') }) } }
const eliminarEquipo = item => { $q.dialog({ title: 'Confirmar eliminación', message: `¿Eliminar el equipo ${item.tipo}?`, cancel: true, persistent: true }).onOk(async () => { try { await api.delete(`/equipos/${item.id}`); $q.notify({ type: 'positive', message: 'Equipo eliminado correctamente' }); cargarEquipos() } catch (err) { $q.notify({ type: 'negative', message: extraerMensajeError(err, 'No se pudo eliminar el equipo') }) } }) }
onMounted(() => { cargarEquipos(); cargarClientes() })
</script>
