<template>
  <q-page class="q-pa-md page-shell">
    <div class="row items-center justify-between q-mb-md q-col-gutter-md"><div><div class="text-h4 text-weight-bold text-primary">Pagos</div><div class="text-subtitle2 text-grey-7">Registro de pagos de servicios técnicos</div></div><div class="q-gutter-sm"><q-btn color="primary" icon="add" label="Nuevo Pago" @click="abrirCrear" /><q-btn color="primary" outline icon="refresh" label="Actualizar" @click="cargarPagos" /></div></div>
    <q-card class="content-card q-mb-md"><q-card-section><q-input v-model="buscar" outlined dense clearable debounce="400" label="Buscar pago por cliente, estado o método" @update:model-value="cargarPagos"><template #prepend><q-icon name="search" /></template></q-input></q-card-section></q-card>
    <q-banner v-if="error" class="bg-red-1 text-red q-mb-md rounded-borders">{{ error }}</q-banner>
    <q-card class="content-card"><q-table title="Listado de pagos" :rows="pagos" :columns="columns" row-key="id" :loading="loading" no-data-label="No hay pagos registrados"><template #body-cell-monto="props"><q-td :props="props">Bs {{ Number(props.row.monto || 0).toFixed(2) }}</q-td></template><template #body-cell-estado="props"><q-td :props="props"><q-chip dense :color="colorEstado(props.row.estado)" text-color="white">{{ textoEstado(props.row.estado) }}</q-chip></q-td></template><template #body-cell-acciones="props"><q-td :props="props" class="table-actions"><q-btn dense flat round color="primary" icon="visibility" @click="abrirVer(props.row)" /><q-btn dense flat round color="warning" icon="edit" @click="abrirEditar(props.row)" /><q-btn dense flat round color="negative" icon="delete" @click="eliminarPago(props.row)" /></q-td></template></q-table></q-card>
    <q-dialog v-model="dialogo"><q-card class="rounded-dialog" style="width: 760px; max-width: 95vw"><q-card-section class="bg-primary text-white"><div class="text-h6">{{ tituloDialogo }}</div></q-card-section><q-card-section class="row q-col-gutter-md"><div class="col-12 col-md-6"><q-select v-model="form.cita_id" :options="citasOptions" emit-value map-options label="Cita" outlined clearable :readonly="modo === 'ver'" @update:model-value="seleccionarCita" /></div><div class="col-12 col-md-6"><q-select v-model="form.cliente_id" :options="clientesOptions" emit-value map-options label="Cliente" outlined clearable :readonly="modo === 'ver'" /></div><div class="col-12 col-md-3"><q-input v-model.number="form.monto" type="number" label="Monto" prefix="Bs" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-3"><q-select v-model="form.metodo_pago" :options="metodosOptions" emit-value map-options label="Método" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-3"><q-select v-model="form.estado" :options="estadosOptions" emit-value map-options label="Estado" outlined :readonly="modo === 'ver'" /></div><div class="col-12 col-md-3"><q-input v-model="form.fecha_pago" type="date" label="Fecha" outlined :readonly="modo === 'ver'" /></div><div class="col-12"><q-input v-model="form.observacion" label="Observación" outlined type="textarea" :readonly="modo === 'ver'" /></div></q-card-section><q-card-actions align="right"><q-btn flat label="Cerrar" color="grey-8" v-close-popup /><q-btn v-if="modo !== 'ver'" color="primary" icon="save" :label="modo === 'crear' ? 'Guardar' : 'Actualizar'" @click="guardarPago" /></q-card-actions></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { date, useQuasar } from 'quasar'
import api, { extraerMensajeError } from '../services/api.js'
const $q = useQuasar()
const loading = ref(false), error = ref(''), buscar = ref(''), pagos = ref([]), citas = ref([]), clientes = ref([]), dialogo = ref(false), modo = ref('crear'), pagoId = ref(null)
const metodosOptions = [{ label: 'Efectivo', value: 'efectivo' }, { label: 'QR', value: 'qr' }, { label: 'Transferencia', value: 'transferencia' }, { label: 'Mixto', value: 'mixto' }]
const estadosOptions = [{ label: 'Pendiente', value: 'pendiente' }, { label: 'Pagado', value: 'pagado' }, { label: 'Anulado', value: 'anulado' }]
const formInicial = { cita_id: null, cliente_id: null, monto: 0, metodo_pago: 'efectivo', estado: 'pagado', fecha_pago: date.formatDate(new Date(), 'YYYY-MM-DD'), observacion: '' }
const form = ref({ ...formInicial })
const clientesOptions = computed(() => clientes.value.map(c => ({ label: c.nombre, value: c.id })))
const citasOptions = computed(() => citas.value.map(c => ({ label: `${c.fecha} ${c.hora || ''} - ${c.cliente?.nombre || 'Cliente'} - Bs ${Number(c.total || 0).toFixed(2)}`, value: c.id, cliente_id: c.cliente_id || c.cliente?.id || null, total: Number(c.total || 0) })))
const columns = [{ name: 'fecha_pago', label: 'Fecha', field: 'fecha_pago', align: 'left', sortable: true }, { name: 'cliente', label: 'Cliente', field: row => row.cliente?.nombre || 'Sin cliente', align: 'left' }, { name: 'servicio', label: 'Servicio', field: row => row.cita?.servicio?.nombre || 'Sin servicio', align: 'left' }, { name: 'monto', label: 'Monto', field: 'monto', align: 'right' }, { name: 'metodo_pago', label: 'Método', field: 'metodo_pago', align: 'left' }, { name: 'estado', label: 'Estado', field: 'estado', align: 'center' }, { name: 'acciones', label: 'Acciones', field: 'acciones', align: 'center' }]
const tituloDialogo = computed(() => modo.value === 'crear' ? 'Registrar pago' : modo.value === 'editar' ? 'Editar pago' : 'Ver pago')
const textoEstado = estado => estadosOptions.find(item => item.value === estado)?.label || estado
const colorEstado = estado => ({ pendiente: 'warning', pagado: 'positive', anulado: 'negative' }[estado] || 'grey')
const limpiarFormulario = () => { form.value = { ...formInicial }; pagoId.value = null }
const cargarCombos = async () => { const [c, cli] = await Promise.all([api.get('/citas'), api.get('/clientes')]); citas.value = c.data.data || []; clientes.value = cli.data.data || [] }
const cargarPagos = async () => { loading.value = true; error.value = ''; try { const r = await api.get('/pagos', { params: { buscar: buscar.value || undefined } }); pagos.value = r.data.data || [] } catch (err) { error.value = extraerMensajeError(err, 'No se pudo cargar la lista de pagos.') } finally { loading.value = false } }
const seleccionarCita = value => { const opt = citasOptions.value.find(c => c.value === value); if (opt) { form.value.cliente_id = opt.cliente_id; form.value.monto = opt.total } }
const abrirCrear = async () => { modo.value = 'crear'; limpiarFormulario(); await cargarCombos(); dialogo.value = true }
const abrirVer = async item => { modo.value = 'ver'; pagoId.value = item.id; await cargarCombos(); form.value = { ...item, cita_id: item.cita_id || item.cita?.id || null, cliente_id: item.cliente_id || item.cliente?.id || null }; dialogo.value = true }
const abrirEditar = async item => { modo.value = 'editar'; pagoId.value = item.id; await cargarCombos(); form.value = { ...item, cita_id: item.cita_id || item.cita?.id || null, cliente_id: item.cliente_id || item.cliente?.id || null }; dialogo.value = true }
const guardarPago = async () => { if (!form.value.monto) { $q.notify({ type: 'warning', message: 'El monto es obligatorio' }); return } try { if (modo.value === 'crear') await api.post('/pagos', form.value); else await api.put(`/pagos/${pagoId.value}`, form.value); $q.notify({ type: 'positive', message: 'Pago guardado correctamente' }); dialogo.value = false; limpiarFormulario(); cargarPagos() } catch (err) { $q.notify({ type: 'negative', message: extraerMensajeError(err, 'No se pudo guardar el pago') }) } }
const eliminarPago = item => { $q.dialog({ title: 'Confirmar eliminación', message: `¿Eliminar este pago?`, cancel: true, persistent: true }).onOk(async () => { try { await api.delete(`/pagos/${item.id}`); $q.notify({ type: 'positive', message: 'Pago eliminado correctamente' }); cargarPagos() } catch (err) { $q.notify({ type: 'negative', message: extraerMensajeError(err, 'No se pudo eliminar el pago') }) } }) }
onMounted(() => { cargarPagos(); cargarCombos() })
</script>
